export const PERMISSIONS = {
  // roles
  CREATE_ROLE: "create-role",
  EDIT_ROLE: "edit-role",
  DELETE_ROLE: "delete-role",
  ASSIGN_ROLE: "assign-role",
  VIEW_ROLE: "view-role",
  // tasks
  CREATE_TASK: "create-task",
  EDIT_TASK: "edit-task",
  DELETE_TASK: "delete-task",
  ASSIGN_TASK: "assign-task",
  VIEW_TASK: "view-task",
  // projects
  MANAGE_PROJECT: "manage-project",
  CREATE_PROJECT: "create-project",
  EDIT_PROJECT: "edit-project",
  DELETE_PROJECT: "delete-project",
  VIEW_PROJECT: "view-project",
  // columns
  CREATE_COLUMN: "create-column",
  EDIT_COLUMN: "edit-column",
  DELETE_COLUMN: "delete-column",
  // users
  CREATE_USER: "create-user",
  EDIT_USER: "edit-user",
  DELETE_USER: "delete-user",
  VIEW_USER: "view-user",
  // dashboard
  VIEW_DASHBOARD: "view-dashboard",
  // company
  EDIT_COMPANY: "edit-company",
  DELETE_COMPANY: "delete-company",
  CREATE_COMPANY: "create-company",
  VIEW_COMPANY: "view-company",
}
