import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import { HeaderNav } from "@/components/HeaderNav"
import { getServerSession } from "next-auth/next"
import { authOptions } from "./api/auth/[...nextauth]/route"
import SessionAuthProvider from "@/context/SessionAuthProvider"
import { AsideResposive } from "@/components/Aside"
import { AsideProvider } from "@/context/AsideResponsiveProvider"
import { ThemeProvider } from "@/providers/theme-provider"

// const inter = Inter({ subsets: ["latin"] })
const firaCode = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type RootLayoutProps = Readonly<{ children: React.ReactNode }>

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${firaCode.className} antialiased`}>
        <SessionAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <AsideProvider>
              <div className="flex h-screen">
                <AsideResposive />
                <div className="flex-1">
                  <HeaderNav />
                  <main
                    className={`overflow-auto p-5 w-full ${
                      session ? "h-screen-80" : "h-screen"
                    }`}
                  >
                    {children}
                  </main>
                </div>
              </div>
            </AsideProvider>
          </ThemeProvider>
        </SessionAuthProvider>
      </body>
    </html>
  )
}
