import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import { getServerSession } from "next-auth/next"
import { authOptions } from "./api/auth/[...nextauth]/route"
import SessionAuthProvider from "@/context/SessionAuthProvider"
import { AsideProvider } from "@/context/AsideResponsiveProvider"
import { ThemeProvider } from "@/providers/theme-provider"
import { Main } from "./main"

// const inter = Inter({ subsets: ["latin"] })
const firaCode = Montserrat({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type RootLayoutProps = Readonly<{ children: React.ReactNode }>

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${firaCode.className} antialiased`}>
        <SessionAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <AsideProvider>
              <Main>{children}</Main>
            </AsideProvider>
          </ThemeProvider>
        </SessionAuthProvider>
      </body>
    </html>
  )
}
